/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institute_management;

import com.institute.db.DB;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author pasindu hathurushigh
 */
public class EmployeeManagement extends javax.swing.JFrame {

    private Design design;

    /**
     * Creates new form EmployeeManagement
     */
    public EmployeeManagement() {
        initComponents();
        generateEmployeeID();
        this.setIconImage(design.getIconImage());
    }

    {
        design = new Design();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_empid = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_addline1 = new javax.swing.JTextField();
        txt_addline2 = new javax.swing.JTextField();
        txt_addline3 = new javax.swing.JTextField();
        txt_contact1 = new javax.swing.JTextField();
        txt_contact2 = new javax.swing.JTextField();
        rad_active = new javax.swing.JRadioButton();
        rad_inactive = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        rad_male = new javax.swing.JRadioButton();
        rad_female = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Management");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    EMPLOYEE");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Employee ID");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setText("NIC");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setText("Address Line1");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setText("Address Line2");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setText("Address Line3");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setText("Contact Number");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setText("Status");

        txt_empid.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        txt_nic.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        txt_fname.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        txt_lname.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        txt_addline1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        txt_addline2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        txt_addline3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        txt_contact1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txt_contact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contact1KeyTyped(evt);
            }
        });

        txt_contact2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txt_contact2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contact2KeyTyped(evt);
            }
        });

        buttonGroup2.add(rad_active);
        rad_active.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        rad_active.setSelected(true);
        rad_active.setText("Active");
        rad_active.setFocusPainted(false);

        buttonGroup2.add(rad_inactive);
        rad_inactive.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        rad_inactive.setText("Inactive");
        rad_inactive.setFocusPainted(false);

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/saveicon.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/updateicon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/searchicon.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/deleteicon.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setText("Email");

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setText("Gender");

        txt_email.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        buttonGroup1.add(rad_male);
        rad_male.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        rad_male.setSelected(true);
        rad_male.setText("Male");
        rad_male.setFocusPainted(false);

        buttonGroup1.add(rad_female);
        rad_female.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        rad_female.setText("Female");
        rad_female.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_empid)
                                .addComponent(txt_nic)
                                .addComponent(txt_fname)
                                .addComponent(txt_lname)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_addline3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_addline2))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rad_active)
                                    .addGap(31, 31, 31)
                                    .addComponent(rad_inactive))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_contact1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_contact2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                                .addComponent(txt_email)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rad_male)
                                    .addGap(45, 45, 45)
                                    .addComponent(rad_female)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(txt_addline1))))
                    .addComponent(jLabel11))
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_empid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_addline1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rad_male)
                                .addComponent(rad_female)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_addline2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_addline3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_contact1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_contact2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rad_active)
                            .addComponent(rad_inactive)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_contact1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contact1KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_contact1KeyTyped

    private void txt_contact2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contact2KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_contact2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txt_fname.getText().equals("") && txt_fname.getText() != null
                && !txt_lname.getText().equals("") && txt_lname.getText() != null
                && !txt_nic.getText().equals("") && txt_nic.getText() != null
                && !txt_addline1.getText().equals("") && txt_addline1.getText() != null
                && !txt_addline2.getText().equals("") && txt_addline2.getText() != null
                && !txt_contact1.getText().equals("") && txt_contact1.getText() != null
                && !txt_email.getText().equals("") && txt_email.getText() != null) {
            String gender = (rad_male.isSelected()) ? "MALE" : "FEMALE";
            int status = (rad_active.isSelected()) ? 1 : 0;
            try {
                DB.push("INSERT INTO address(`address_line1`,`address_line2`,`address_line3`) VALUES('"
                        + txt_addline1.getText().toUpperCase().trim() + "','"
                        + txt_addline2.getText().toUpperCase().trim() + "','"
                        + txt_addline3.getText().toUpperCase().trim() + "')");

                ResultSet rs = DB.search("SELECT `id` FROM address WHERE `address_line1`='"
                        + txt_addline1.getText().trim() + "' AND `address_line2`='"
                        + txt_addline2.getText().trim() + "' AND `address_line3`='"
                        + txt_addline3.getText().trim() + "'");
                if (rs.next()) {
                    DB.push("INSERT INTO employee VALUES('"
                            + txt_empid.getText().trim() + "','"
                            + txt_fname.getText().toUpperCase().trim() + "','"
                            + txt_lname.getText().toUpperCase().trim() + "','"
                            + txt_nic.getText().trim() + "','"
                            + gender + "','"
                            + rs.getString("id") + "','"
                            + txt_contact1.getText().trim() + "','"
                            + txt_contact2.getText().trim() + "','"
                            + txt_email.getText() + "','" + status + "')");
                }
                String fullName = txt_fname.getText() + " " + txt_lname.getText();
                SystemUserManagement suser = new SystemUserManagement(txt_empid.getText(), txt_nic.getText(), fullName, this);
                suser.setVisible(true);
            } catch (java.sql.SQLIntegrityConstraintViolationException e) {
                JOptionPane.showMessageDialog(this, "An employee already registered from this EmployeeID or NIC!",
                        "Error", JOptionPane.ERROR_MESSAGE, design.getErrorIcon());
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill all mandatory fields", "",
                    JOptionPane.WARNING_MESSAGE, design.getWarningIcon());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!txt_nic.getText().equals("")) {
            try {
                ResultSet rs = DB.search("SELECT * FROM employee e INNER JOIN address a ON e.`address`=a.`id`"
                        + " WHERE `nic`='" + txt_nic.getText() + "'");
                if (rs.next()) {
                    txt_empid.setText(rs.getString("employeeid"));
                    txt_fname.setText(rs.getString("fname"));
                    txt_lname.setText(rs.getString("lname"));
                    txt_contact1.setText(rs.getString("contactno1"));
                    txt_contact2.setText(rs.getString("contactno2"));
                    txt_email.setText(rs.getString("email"));
                    if (rs.getString("gender").equals("MALE")) {
                        rad_male.setSelected(true);
                    } else {
                        rad_female.setSelected(true);
                    }
                    if (rs.getString("status").equals("1")) {
                        rad_active.setSelected(true);
                    } else {
                        rad_inactive.setSelected(true);
                    }
                    txt_addline1.setText(rs.getString("address_line1"));
                    txt_addline2.setText(rs.getString("address_line2"));
                    txt_addline3.setText(rs.getString("address_line3"));

                } else {
                    JOptionPane.showMessageDialog(this, "No registred employee from this NIC");
                    clearFields();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter NIC to search", "",
                    JOptionPane.WARNING_MESSAGE, design.getWarningIcon());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!txt_fname.getText().equals("") && txt_fname.getText() != null
                && !txt_lname.getText().equals("") && txt_lname.getText() != null
                && !txt_nic.getText().equals("") && txt_nic.getText() != null
                && !txt_addline1.getText().equals("") && txt_addline1.getText() != null
                && !txt_addline2.getText().equals("") && txt_addline2.getText() != null
                && !txt_contact1.getText().equals("") && txt_contact1.getText() != null
                && !txt_email.getText().equals("") && txt_email.getText() != null) {
            String gender = (rad_male.isSelected()) ? "MALE" : "FEMALE";
            int status = (rad_active.isSelected()) ? 1 : 0;
            try {
                ResultSet rs = DB.search("SELECT `address` FROM employee WHERE `nic`='"
                        + txt_nic.getText() + "'");
                if (rs.next()) {
                    DB.push("UPDATE address SET `address_line1`='"
                            + txt_addline1.getText().toUpperCase().trim() + "',`address_line2`='"
                            + txt_addline2.getText().toUpperCase().trim() + "',`address_line3`='"
                            + txt_addline3.getText().toUpperCase().trim() + "' WHERE `id`='"
                            + rs.getString("address") + "'");
                    DB.push("UPDATE employee SET `fname`='"
                            + txt_fname.getText().toUpperCase().trim() + "',`lname`='"
                            + txt_lname.getText().toUpperCase().trim() + "',`gender`='"
                            + gender + "',`contactno1`='"
                            + txt_contact1.getText().trim() + "',`contactno2`='"
                            + txt_contact2.getText().trim() + "',`email`='"
                            + txt_email.getText().trim() + "',`status`='"
                            + status + "' WHERE `nic`='" + txt_nic.getText().trim() + "'");
                    JOptionPane.showMessageDialog(this, "Employee updated sucessfully", "",
                            JOptionPane.PLAIN_MESSAGE, design.getSuccessIcon());
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No registered employee from this NIC. Register employee first", "",
                            JOptionPane.WARNING_MESSAGE, design.getWarningIcon());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill all mandatory fields!", "",
                    JOptionPane.PLAIN_MESSAGE, design.getWarningIcon());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (!txt_nic.getText().equals("")) {
                ResultSet rs = DB.search("SELECT `fname`,`lname` FROM employee WHERE `nic`='"
                        + txt_nic.getText().trim() + "'");
                if (rs.next()) {
                    int confirmOption = JOptionPane.showConfirmDialog(this,
                            "Are you sure delete this employee "
                            + txt_nic.getText() + "-" + rs.getString("fname") + " " + rs.getString("lname") + "?",
                            "Delete Employee", JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE, design.getQuestionIcon());
                    if (confirmOption == JOptionPane.YES_OPTION) {
                        DB.push("UPDATE employee SET `status`='0' WHERE `nic`='" + txt_nic.getText() + "'");
                        clearFields();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No registered employee from this NIC", "",
                            JOptionPane.WARNING_MESSAGE, design.getWarningIcon());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        Home.empManage = null;
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rad_active;
    private javax.swing.JRadioButton rad_female;
    private javax.swing.JRadioButton rad_inactive;
    private javax.swing.JRadioButton rad_male;
    private javax.swing.JTextField txt_addline1;
    private javax.swing.JTextField txt_addline2;
    private javax.swing.JTextField txt_addline3;
    private javax.swing.JTextField txt_contact1;
    private javax.swing.JTextField txt_contact2;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_nic;
    // End of variables declaration//GEN-END:variables

    private void generateEmployeeID() {
        try {
            ResultSet rs = DB.search("SELECT COUNT(employeeid) AS countempid FROM employee");
            if (rs.next()) {
                int count = rs.getInt("countempid");
                txt_empid.setText("EMP" + (++count));
                txt_nic.grabFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clearFields() {
        generateEmployeeID();
        txt_nic.setText(null);
        txt_fname.setText(null);
        txt_lname.setText(null);
        txt_addline1.setText(null);
        txt_addline2.setText(null);
        txt_addline3.setText(null);
        txt_contact1.setText(null);
        txt_contact2.setText(null);
        txt_email.setText(null);
        rad_active.setSelected(true);
        rad_male.setSelected(true);
    }
}
