/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institute_management;

import com.institute.common.DateAndTime;
import com.institute.common.SystemConfigData;
import com.institute.db.DB;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author pasindu hathurushigh
 */
public class Home extends javax.swing.JFrame {

    private Date date;
    private SimpleDateFormat sdf;
    private Design design;
    static EmployeeManagement empManage;
    static Payment payment;
    static Attendance attendance1;
    static Attendance attendance2;
    static StudentClassRegistration classRegistration;
    static StudentManagement smanage;
    static TeacherManagement tmanage;
    static ClassManagement cmanage;
    static ClassSchedule schedule;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        if (SystemConfigData.getUsertype().equals("USR")) {
            jPanel19.setVisible(false);
            report_btn.setVisible(false);
            settings_btn.setVisible(false);
        }
        setDateAndTime();
        if (SystemConfigData.getUsertype().equals("ADM")) {
            lbl_usertype.setText("ADMIN");
        } else {
            lbl_usertype.setText("USER");
        }
        lbl_username.setText(SystemConfigData.getUsername());
        lbl_empid.setText(SystemConfigData.getUserid());
        design = new Design();
        loadHome();
        getRootPane().setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 3));
    }

    {
        sdf = new SimpleDateFormat("HH:mm:ss a");
        date = new Date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movepane = new javax.swing.JPanel();
        closebtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        settings_btn = new javax.swing.JPanel();
        btn_settings = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        home_btn = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        todayclass_btn = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        task_btn = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        todayprogress_btn = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        report_btn = new javax.swing.JPanel();
        btn_report = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        acccount_btn = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_home = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lbl_teachericon = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_empid = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_usertype = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panel_futureclass = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        table_yetstart = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        table_inprogress = new javax.swing.JTable();
        panel_pastclass = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_todayprogress = new javax.swing.JTable();
        jButton25 = new javax.swing.JButton();
        panel_note = new javax.swing.JPanel();
        panel_analyse = new javax.swing.JPanel();
        panel_settingsadmin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movepane.setBackground(new java.awt.Color(51, 51, 51));
        movepane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movepaneMouseDragged(evt);
            }
        });
        movepane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movepaneMousePressed(evt);
            }
        });

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/closeicon.png"))); // NOI18N
        closebtn.setBorder(null);
        closebtn.setBorderPainted(false);
        closebtn.setContentAreaFilled(false);
        closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebtn.setFocusPainted(false);
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebtnMouseExited(evt);
            }
        });
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout movepaneLayout = new javax.swing.GroupLayout(movepane);
        movepane.setLayout(movepaneLayout);
        movepaneLayout.setHorizontalGroup(
            movepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movepaneLayout.createSequentialGroup()
                .addContainerGap(1170, Short.MAX_VALUE)
                .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        movepaneLayout.setVerticalGroup(
            movepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movepaneLayout.createSequentialGroup()
                .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        getContentPane().add(movepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 80));

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings_btn.setBackground(new java.awt.Color(0, 51, 102));
        settings_btn.setForeground(new java.awt.Color(204, 255, 255));
        settings_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_settings.setContentAreaFilled(false);
        btn_settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_settings.setFocusPainted(false);
        btn_settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingsActionPerformed(evt);
            }
        });
        settings_btn.add(btn_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 60));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/settingsicon.png"))); // NOI18N
        jLabel19.setText("   Settings & Config");
        settings_btn.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 190, 41));

        jPanel6.add(settings_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 280, 60));

        home_btn.setBackground(new java.awt.Color(0, 51, 102));
        home_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        home_btn.setForeground(new java.awt.Color(204, 255, 255));
        home_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(0, 51, 102));
        btn_home.setBorder(null);
        btn_home.setBorderPainted(false);
        btn_home.setContentAreaFilled(false);
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.setFocusPainted(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        home_btn.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 60));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/homeicon.png"))); // NOI18N
        jLabel2.setText("    Home");
        home_btn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 124, 41));

        jPanel6.add(home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 60));

        todayclass_btn.setBackground(new java.awt.Color(0, 51, 102));
        todayclass_btn.setForeground(new java.awt.Color(204, 255, 255));
        todayclass_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        todayclass_btn.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 60));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/yettoicon.png"))); // NOI18N
        jLabel3.setText("   Today Classes");
        todayclass_btn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 220, 41));

        jPanel6.add(todayclass_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 280, 60));

        task_btn.setBackground(new java.awt.Color(0, 51, 102));
        task_btn.setForeground(new java.awt.Color(204, 255, 255));
        task_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        task_btn.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 60));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/taskicon.png"))); // NOI18N
        jLabel4.setText("  Tasks & Notes");
        task_btn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 190, 41));

        jPanel6.add(task_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, 60));

        todayprogress_btn.setBackground(new java.awt.Color(0, 51, 102));
        todayprogress_btn.setForeground(new java.awt.Color(204, 255, 255));
        todayprogress_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        todayprogress_btn.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 60));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/inprogress1.png"))); // NOI18N
        jLabel9.setText("   Today Progress");
        todayprogress_btn.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 170, 41));

        jPanel6.add(todayprogress_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 280, 60));

        lbl_date.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(153, 204, 255));
        jPanel6.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 220, 30));

        lbl_time.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(153, 204, 255));
        lbl_time.setText("Time");
        jPanel6.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 150, 30));

        report_btn.setBackground(new java.awt.Color(0, 51, 102));
        report_btn.setForeground(new java.awt.Color(204, 255, 255));
        report_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_report.setContentAreaFilled(false);
        btn_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_report.setFocusPainted(false);
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        report_btn.add(btn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 60));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/reporticon.png"))); // NOI18N
        jLabel24.setText("   Report & Analyze");
        report_btn.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 190, 41));

        jPanel6.add(report_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 280, 60));

        acccount_btn.setBackground(new java.awt.Color(0, 51, 102));
        acccount_btn.setForeground(new java.awt.Color(204, 255, 255));
        acccount_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setFocusPainted(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        acccount_btn.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 60));

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/accounticon.png"))); // NOI18N
        jLabel30.setText("    Account");
        acccount_btn.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 190, 41));

        jPanel6.add(acccount_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 280, 60));

        logout_btn.setBackground(new java.awt.Color(0, 51, 102));
        logout_btn.setForeground(new java.awt.Color(204, 255, 255));
        logout_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setContentAreaFilled(false);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.setFocusPainted(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        logout_btn.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 60));

        jLabel37.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/logouticon.png"))); // NOI18N
        jLabel37.setText("   Log out");
        logout_btn.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 190, 41));

        jPanel6.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 280, 60));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 720));

        panel_home.setBackground(new java.awt.Color(153, 204, 255));

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 230));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Student");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 140, 180, 38));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/studenticon.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jPanel10.setBackground(new java.awt.Color(153, 255, 255));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.setFocusPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 230));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Class Registration");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 143, 180, 38));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/registrationicon.png"))); // NOI18N
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 180, 90));

        jPanel12.setBackground(new java.awt.Color(153, 255, 255));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 230));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Teacher");
        jPanel12.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 142, 180, 38));

        lbl_teachericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/teachericon.png"))); // NOI18N
        jPanel12.add(lbl_teachericon, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 54, 64, 64));

        jPanel19.setBackground(new java.awt.Color(153, 255, 255));
        jPanel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        jPanel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 230));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 153));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Employee");
        jPanel19.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 38));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/employeeicon.png"))); // NOI18N
        jPanel19.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jPanel13.setBackground(new java.awt.Color(153, 255, 255));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        jPanel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 230));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Payment");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 143, 159, 38));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/paymenticon.png"))); // NOI18N
        jPanel13.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 48, 170, 89));

        jPanel14.setBackground(new java.awt.Color(153, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 230));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Attendance");
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 140, 170, 38));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/attendance.png"))); // NOI18N
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 48, -1, 77));

        jPanel15.setBackground(new java.awt.Color(153, 255, 255));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setFocusPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 230));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Schedule");
        jPanel15.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 38));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/scheduleicon.png"))); // NOI18N
        jPanel15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOME");

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 204, 255));
        jLabel20.setText("Employee ID :");

        lbl_empid.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_empid.setForeground(new java.awt.Color(255, 255, 255));
        lbl_empid.setText("lbl_2");

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 204, 255));
        jLabel25.setText("UserType :");

        lbl_usertype.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_usertype.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usertype.setText("lbl_3");

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 204, 255));
        jLabel26.setText("Welcome,");

        lbl_username.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("lbl_1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_empid, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_usertype, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_usertype))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_empid))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel16.setBackground(new java.awt.Color(153, 255, 255));
        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        jPanel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 230));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 153));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Classes");
        jPanel16.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 143, 156, 38));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/institute/images/classico.png"))); // NOI18N
        jPanel16.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 89));

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", panel_home);

        panel_futureclass.setBackground(new java.awt.Color(153, 204, 255));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 153));
        jLabel23.setText("Yet to start");

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 153));
        jLabel27.setText("In Progress");

        table_yetstart.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        table_yetstart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grade", "Subject", "Teacher", "Start time", "End time", "Hall"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_yetstart.setRowHeight(20);
        jScrollPane8.setViewportView(table_yetstart);
        if (table_yetstart.getColumnModel().getColumnCount() > 0) {
            table_yetstart.getColumnModel().getColumn(0).setPreferredWidth(20);
            table_yetstart.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_yetstart.getColumnModel().getColumn(2).setPreferredWidth(150);
            table_yetstart.getColumnModel().getColumn(3).setPreferredWidth(20);
            table_yetstart.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        table_inprogress.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        table_inprogress.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grade", "Subject", "Teacher", "Start time", "End time", "Hall"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_inprogress.setRowHeight(20);
        jScrollPane9.setViewportView(table_inprogress);
        if (table_inprogress.getColumnModel().getColumnCount() > 0) {
            table_inprogress.getColumnModel().getColumn(0).setPreferredWidth(20);
            table_inprogress.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_inprogress.getColumnModel().getColumn(2).setPreferredWidth(150);
            table_inprogress.getColumnModel().getColumn(3).setPreferredWidth(20);
            table_inprogress.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        javax.swing.GroupLayout panel_futureclassLayout = new javax.swing.GroupLayout(panel_futureclass);
        panel_futureclass.setLayout(panel_futureclassLayout);
        panel_futureclassLayout.setHorizontalGroup(
            panel_futureclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_futureclassLayout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(panel_futureclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel23)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panel_futureclassLayout.setVerticalGroup(
            panel_futureclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_futureclassLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", panel_futureclass);

        panel_pastclass.setBackground(new java.awt.Color(153, 204, 255));

        table_todayprogress.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        table_todayprogress.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grade", "Subject", "Teacher", "Time", "Hall", "Is Held", "Attendees"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_todayprogress.setFocusable(false);
        table_todayprogress.setOpaque(false);
        table_todayprogress.setRowHeight(25);
        jScrollPane5.setViewportView(table_todayprogress);
        if (table_todayprogress.getColumnModel().getColumnCount() > 0) {
            table_todayprogress.getColumnModel().getColumn(0).setPreferredWidth(20);
            table_todayprogress.getColumnModel().getColumn(1).setPreferredWidth(150);
            table_todayprogress.getColumnModel().getColumn(2).setPreferredWidth(250);
            table_todayprogress.getColumnModel().getColumn(3).setPreferredWidth(100);
            table_todayprogress.getColumnModel().getColumn(4).setPreferredWidth(50);
            table_todayprogress.getColumnModel().getColumn(5).setPreferredWidth(50);
            table_todayprogress.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        jButton25.setBackground(new java.awt.Color(255, 255, 255));
        jButton25.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton25.setText("Print Report");
        jButton25.setContentAreaFilled(false);
        jButton25.setFocusPainted(false);
        jButton25.setOpaque(true);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_pastclassLayout = new javax.swing.GroupLayout(panel_pastclass);
        panel_pastclass.setLayout(panel_pastclassLayout);
        panel_pastclassLayout.setHorizontalGroup(
            panel_pastclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pastclassLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panel_pastclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panel_pastclassLayout.setVerticalGroup(
            panel_pastclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pastclassLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", panel_pastclass);

        panel_note.setBackground(new java.awt.Color(153, 204, 255));
        panel_note.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("tab4", panel_note);

        panel_analyse.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("tab5", panel_analyse);

        panel_settingsadmin.setBackground(new java.awt.Color(153, 204, 255));
        panel_settingsadmin.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("tab6", panel_settingsadmin);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 980, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseEntered
        closebtn.setOpaque(true);
        closebtn.setBackground(new Color(230, 57, 0));
    }//GEN-LAST:event_closebtnMouseEntered

    private void closebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseExited
        closebtn.setOpaque(false);
        closebtn.setBackground(null);
    }//GEN-LAST:event_closebtnMouseExited

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closebtnActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        changeButtonColor(home_btn);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        changeButtonColor(todayclass_btn);
        loadTodayClasses();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (smanage == null) {
            smanage = new StudentManagement();
            smanage.setVisible(true);
        } else {
            smanage.toFront();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (tmanage == null) {
            tmanage = new TeacherManagement();
            tmanage.setVisible(true);
        } else {
            tmanage.toFront();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private int xMouse, yMouse;
    private void movepaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movepaneMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_movepaneMousePressed

    private void movepaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movepaneMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_movepaneMouseDragged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTabbedPane1.setSelectedComponent(panel_pastclass);
        changeButtonColor(todayprogress_btn);
        loadTodayProgress();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (panel_note.getComponentCount() == 0) {
            Note note = new Note();
            panel_note.add(note);
            panel_note.revalidate();
        }
        jTabbedPane1.setSelectedComponent(panel_note);
        changeButtonColor(task_btn);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (cmanage == null) {
            cmanage = new ClassManagement();
            cmanage.setVisible(true);
        } else {
            cmanage.toFront();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (attendance1 == null) {
            attendance1 = new Attendance();
            attendance1.setVisible(true);
        } else if (attendance2 == null) {
            attendance2 = new Attendance();
            attendance2.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (payment == null) {
            payment = new Payment();
            payment.setVisible(true);
        } else {
            payment.toFront();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (schedule == null) {
            schedule = new ClassSchedule();
            schedule.setVisible(true);
        } else {
            schedule.toFront();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (empManage == null) {
            empManage = new EmployeeManagement();
            empManage.setVisible(true);
        } else {
            empManage.toFront();
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        if (panel_analyse.getComponentCount() == 0) {
            ReportAndAnalyse ra = new ReportAndAnalyse();
            panel_analyse.add(ra);
            panel_analyse.revalidate();
        }
        changeButtonColor(report_btn);
        jTabbedPane1.setSelectedComponent(panel_analyse);
    }//GEN-LAST:event_btn_reportActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        SystemUserManagement systemUser = new SystemUserManagement(this);
        systemUser.setVisible(true);
        this.setEnabled(false);
        changeButtonColor(acccount_btn);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void btn_settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingsActionPerformed
        if (panel_settingsadmin.getComponentCount() == 0) {
            Settings settings = new Settings();
            panel_settingsadmin.add(settings);
            panel_settingsadmin.revalidate();
        }
        jTabbedPane1.setSelectedComponent(panel_settingsadmin);
        changeButtonColor(settings_btn);
    }//GEN-LAST:event_btn_settingsActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        if (classRegistration == null) {
            classRegistration = new StudentClassRegistration();
            classRegistration.setVisible(true);
        } else {
            classRegistration.toFront();
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int confirmOption = JOptionPane.YES_OPTION;
        if (empManage != null || smanage != null || tmanage != null || cmanage != null || payment != null
                || attendance1 != null || attendance2 != null || classRegistration != null || schedule != null) {
            confirmOption = JOptionPane.showConfirmDialog(this, "Some processes are in progress, Are you sure to logout!",
                    "Log out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, design.getQuestionIcon());
        }
        if (confirmOption == JOptionPane.YES_OPTION) {
            if (attendance1 != null) {
                attendance1.dispose();
                attendance1 = null;
            }
            if (attendance2 != null) {
                attendance2.dispose();
                attendance2 = null;
            }
            if (smanage != null) {
                smanage.dispose();
                smanage = null;
            }
            if (tmanage != null) {
                tmanage.dispose();
                tmanage = null;
            }
            if (cmanage != null) {
                cmanage.dispose();
                cmanage = null;
            }
            if (payment != null) {
                payment.dispose();
                payment = null;
            }
            if (empManage != null) {
                empManage.dispose();
                empManage = null;
            }
            if (classRegistration != null) {
                classRegistration.dispose();
                classRegistration = null;
            }
            if (schedule != null) {
                schedule.dispose();
                schedule = null;
            }
            Login login = new Login();
            login.setVisible(true);
            SystemConfigData.setUserid(null);
            SystemConfigData.setUsername(null);
            SystemConfigData.setUsertype(null);
            this.dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        try {
            InputStream stream = new FileInputStream("src/com/institute/report/InstituteTodayProgress.jasper");
            JRTableModelDataSource dataSource = new JRTableModelDataSource(table_todayprogress.getModel());
            Map<String, Object> params = new HashMap<>();
            JasperPrint fillReport = JasperFillManager.fillReport(stream, params, dataSource);
            JasperViewer.viewReport(fillReport, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acccount_btn;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_report;
    private javax.swing.JButton btn_settings;
    private javax.swing.JButton closebtn;
    private javax.swing.JPanel home_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_empid;
    private javax.swing.JLabel lbl_teachericon;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_usertype;
    private javax.swing.JPanel logout_btn;
    private javax.swing.JPanel movepane;
    private javax.swing.JPanel panel_analyse;
    private javax.swing.JPanel panel_futureclass;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_note;
    private javax.swing.JPanel panel_pastclass;
    private javax.swing.JPanel panel_settingsadmin;
    private javax.swing.JPanel report_btn;
    private javax.swing.JPanel settings_btn;
    private javax.swing.JTable table_inprogress;
    private javax.swing.JTable table_todayprogress;
    private javax.swing.JTable table_yetstart;
    private javax.swing.JPanel task_btn;
    private javax.swing.JPanel todayclass_btn;
    private javax.swing.JPanel todayprogress_btn;
    // End of variables declaration//GEN-END:variables

    private void loadTodayClasses() {
        try {
            DefaultTableModel dtm1 = (DefaultTableModel) table_inprogress.getModel();
            DefaultTableModel dtm2 = (DefaultTableModel) table_yetstart.getModel();
            dtm1.setRowCount(0);
            dtm2.setRowCount(0);
            //classes yet to start
            ResultSet rs = DB.search("SELECT t.`fname`,t.`lname`,s.`name`,c.`starttime`,c.`endtime`"
                    + ",c.`grade`,ct.`type`,h.`hallname`,h.`floor` FROM class c "
                    + "INNER JOIN subject s ON c.`subject`=s.`id` "
                    + "INNER JOIN teacher t ON c.`teacher`=t.`nic` "
                    + "INNER JOIN classtype ct ON c.`classtype`=ct.`id` "
                    + "INNER JOIN hall h ON c.`hall`=h.`hallno` "
                    + "WHERE c.`classday`='" + DateAndTime.getDateInWord()
                    + "' AND c.`starttime` > '" + DateAndTime.getTime() + "' ORDER BY `starttime` ASC");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("c.grade"));
                v.add(rs.getString("s.name") + "-" + rs.getString("ct.type"));
                v.add(rs.getString("t.fname") + " " + rs.getString("t.lname"));
                v.add(rs.getString("c.starttime"));
                v.add(rs.getString("c.endtime"));
                v.add(rs.getString("h.hallname") + "- FLOOR NO." + rs.getString("h.floor"));
                dtm2.addRow(v);
            }

            //classes in-progress
            rs = DB.search("SELECT t.`fname`,t.`lname`,s.`name`,c.`starttime`,c.`endtime`,"
                    + "c.`grade`,h.`hallname`,h.`floor`,ct.`type` FROM class c "
                    + "INNER JOIN subject s ON c.`subject`=s.`id` "
                    + "INNER JOIN teacher t ON c.`teacher`=t.`nic` "
                    + "INNER JOIN classtype ct ON c.`classtype`=ct.`id` "
                    + "INNER JOIN hall h ON c.`hall`=h.`hallno` "
                    + "WHERE `classday`='" + DateAndTime.getDateInWord() + "' AND '"
                    + DateAndTime.getTime() + "' BETWEEN `starttime` AND `endtime` ORDER BY `starttime` ASC");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("c.grade"));
                v.add(rs.getString("s.name") + "-" + rs.getString("ct.type"));
                v.add(rs.getString("t.fname") + " " + rs.getString("t.lname"));
                v.add(rs.getString("c.starttime"));
                v.add(rs.getString("c.endtime"));
                v.add(rs.getString("h.hallname") + "- FLOOR NO." + rs.getString("h.floor"));
                dtm1.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void loadTodayProgress() {
        //today held classes
        try {
            DefaultTableModel dtm = (DefaultTableModel) table_todayprogress.getModel();
            dtm.setRowCount(0);
            dtm.setRowCount(0);
            ResultSet rs = DB.search("SELECT t.`fname`,t.`lname`,s.`name`,c.`starttime`,c.`endtime`,"
                    + "c.`grade`,c.`hall`,h.`hallname`,c.`classcode`,ct.`type`,h.`floor` FROM class c "
                    + "INNER JOIN subject s ON c.`subject`=s.`id` "
                    + "INNER JOIN teacher t ON c.`teacher`=t.`nic` "
                    + "INNER JOIN classtype ct ON c.`classtype`=ct.`id` "
                    + "INNER JOIN hall h ON c.`hall`=h.`hallno` "
                    + "WHERE c.`classday`='" + DateAndTime.getDateInWord()
                    + "' AND c.`endtime` < '" + DateAndTime.getTime() + "' ORDER BY c.`grade` ASC");

            while (rs.next()) {
                ResultSet rs_get = DB.search("SELECT `id` FROM attendance WHERE `classcode`='"
                        + rs.getString("c.classcode") + "' AND date='" + DateAndTime.getDate() + "'");
                Vector v = new Vector();
                short studentCount = 0;
                String classStat = "NOT HELD";
                if (rs_get.next()) {
                    classStat = "HELD";
                    ResultSet rs_count = DB.search("SELECT COUNT(*) AS studentcount FROM attendance_mark"
                            + " WHERE `attendanceid`='" + rs_get.getString("id") + "'");
                    if (rs_count.next()) {
                        studentCount = rs_count.getShort("studentcount");
                    }
                }
                v.add(rs.getString("c.grade"));
                v.add(rs.getString("s.name") + "-" + rs.getString("ct.type"));
                v.add(rs.getString("t.fname") + " " + rs.getString("t.lname"));
                v.add(rs.getString("c.starttime") + "-" + rs.getString("c.endtime"));
                v.add(rs.getString("c.hall"));
                v.add(classStat);
                v.add(studentCount);
                dtm.addRow(v);
            }

            ResultSet rs_next = DB.search("SELECT `classcode`,`id` FROM attendance WHERE classcode IN"
                    + " (SELECT `classcode` FROM class WHERE `classday`!='"
                    + DateAndTime.getDateInWord() + "') AND `date`='" + DateAndTime.getDate() + "'");
            while (rs_next.next()) {
                ResultSet rs_second = DB.search("SELECT t.`fname`,t.`lname`,s.`name`,c.`starttime`,"
                        + "c.`endtime`,c.`grade`,c.`hall`,h.`hallname`,c.`classcode`,ct.`type`,h.`floor` FROM class c "
                        + "INNER JOIN subject s ON c.`subject`=s.`id` "
                        + "INNER JOIN teacher t ON c.`teacher`=t.`nic` "
                        + "INNER JOIN classtype ct ON c.`classtype`=ct.`id` "
                        + "INNER JOIN hall h ON c.`hall`=h.`hallno` "
                        + "WHERE c.classcode='" + rs_next.getString("classcode") + "'");
                if (rs_second.next()) {
                    ResultSet rs_count = DB.search("SELECT COUNT(*) AS studentcount FROM attendance_mark "
                            + "WHERE `attendanceid`='" + rs_next.getString("id") + "'");
                    if (rs_count.next()) {
                        Vector v = new Vector();
                        int studentCount = rs_count.getInt("studentcount");
                        v.add(rs_second.getString("c.grade"));
                        v.add(rs_second.getString("s.name") + "-" + rs_second.getString("ct.type"));
                        v.add(rs_second.getString("t.fname") + " " + rs_second.getString("t.lname"));
                        v.add("");
                        v.add(rs_second.getString("c.hall"));
                        v.add("HELD");
                        v.add(studentCount);
                        dtm.addRow(v);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setDateAndTime() {
        lbl_date.setText(DateAndTime.getDate() + " " + DateAndTime.getDateInWord());
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {

                Timer timer = new Timer(1000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        date = new Date();
                        lbl_time.setText(sdf.format(date));
                    }
                });
                timer.start();

            }
        });

        thread.start();
    }

    private void loadHome() {
        setIconImage(design.getIconImage());
        home_btn.setBackground(new Color(51, 153, 255));

        designTables(table_yetstart);
        designTables(table_inprogress);
        designTables(table_todayprogress);

    }

    private void changeButtonColor(javax.swing.JPanel btn) {
        report_btn.setBackground(null);
        home_btn.setBackground(null);
        todayclass_btn.setBackground(null);
        todayprogress_btn.setBackground(null);
        settings_btn.setBackground(null);
        task_btn.setBackground(null);
        acccount_btn.setBackground(null);
        btn.setBackground(new Color(51, 153, 255));
    }

    private void designTables(JTable table) {
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 12));
        table.getTableHeader().setForeground(Color.WHITE);
        table.getTableHeader().setBackground(new Color(0, 51, 102));
    }
}
